### PR TITLE
Implemented Szymkiewicz–Simpson coefficient and tests

### LINKED ISSUE #7: Implement Szymkiewicz–Simpson coefficient
Reference: https://en.wikipedia.org/wiki/Overlap_coefficient

### PR DESCRIPTION
**Pull request by jordanmontt**
This should close #7 
This coefficient only works on sets. Please review.
I added the method on Collection class in case is called from an array. And it will be converted into a set any way. I don't if it's correct or if I should create the method in Set class and raise an error when is called with non-sets. What do you say? @hernanmd

### CODE REVIEW

**Comment by hernanmd** [comment]
It seems correct, although I would specialize the implementation where it actually works.
Let the user manage necessary transformations, because asSet could eliminate user collection behind the scenes if this algorithm is applied without care.

What I would like also is to determine if it is O(n) or O(m + n).

**Review by hernanmd — CHANGES_REQUESTED** [review]
See comments in PR

**Comment by jordanmontt** [comment]
I think that the algorithm is O(n) where n es the biggest size of the sets. Because the intersection method in Set is:
```Smalltalk
	| outputSet |
	outputSet := self class new.
	aCollection do: [ :each | 
		(self includes: each) ifTrue: [ outputSet add: each ] ].
	^ outputSet
```
So, does a `do:` for the second set, called `aCollection` , and then does an `includes:` for each element of `aCollection`. But as a set is a Hashed collection the find operation should not be linear but constant time. Then the overlap algorithm takes the size of each of the set, again linear time. So it is O(n)

**Comment by jordanmontt** [comment]
I will merge because I moved the implementation of the method to `Set` class instead of `Collection` class.

**Pull request merged**
